---
- name: Create directories
  file:
    path: "{{grafana_versioned_hostdir}}/{{ item.path }}"
    state: directory
    mode: '{{ item.mode }}'
  with_filetree: "{{playbook_dir}}/setup/"
  when: item.state == 'directory'
- name: Template files
  template:
    src: '{{ item.src }}'
    dest: "{{grafana_versioned_hostdir}}/{{ item.path }}"
    mode: '{{ item.mode }}'
    trim_blocks: false
  with_filetree: "{{playbook_dir}}/setup/"
  when:
  - "item.state == 'file'"
  - "not item.path|regex_search('\\.frep$|conf.d|maintenance.*\\.py')"
- name: Copy files
  copy:
    src: '{{ item.src }}'
    dest: "{{grafana_versioned_hostdir}}/{{ item.path }}"
    mode: '{{ item.mode }}'
  with_filetree: "{{playbook_dir}}/setup/"
  when:
  - "item.state == 'file'"
  - "     item.path|regex_search('\\.frep$|conf.d|maintenance.*\\.py')"
- blockinfile:
    create: true
    path: "{{grafana_hostdir}}/.env"
    content: "{{grafana_docker_dot_env}}"
    marker: "# ANSIBLE MANAGED BLOCK :: deploy commit :: {mark}"
