version: "3.8"
x-env: &env
  env_file: [ .env ]
x-restart: &restart
  restart: unless-stopped
x-log: &log
  depends_on: [log]
  logging: {driver: syslog, options: {tag: '{{'{{'}}index .ContainerLabels "com.docker.compose.service"}}', syslog-address: "tcp://$GRAFANA_SYSLOG_NET"}}
services:
  log:
    <<: [ *restart, *env ]
    image: corpusops/rsyslog
    volumes: [logs:/var/log]
    ports: ["$GRAFANA_SYSLOG_NET:10514"]
  influxdb:
    <<: [ *log, *restart, *env ]
    image: "$INFLUXDB_IMAGE"
    container_name: "influxdb"
    ports: ['${GRAFANA_LISTEN_INT_IF:-127.0.0.1}:8086:8086']
    volumes: [influxdb_data:/var/lib/influxdb]
  grafana:
    <<: [ *log, *restart, *env ]
    image: "$GRAFANA_IMAGE"
    container_name: "grafana"
    depends_on: [influxdb, log]
    ports: ['${GRAFANA_LISTEN_INT_IF:-127.0.0.1}:3000:3000']
    volumes: [grafana_data:/var/lib/grafana, ./grafana:/etc/grafana]
  renderer:
    image: "$GRAFANA_RENDERER_IMAGE"
    ports: ['${GRAFANA_LISTEN_INT_IF:-127.0.0.1}:3001:8081']
volumes:
  grafana_data: {}
  influxdb_data: {}
  logs: {}
